type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
date = "2024-2025 Academic Year"
awards = ["University First-Class Scholarships", "Zhejiang Provincial Government Scholarship"]
suffix = "twice"

[[items]]
date = "2023-2024 Academic Year"
awards = ["University First-Class Scholarships", "Zhejiang Provincial Government Scholarship"]
suffix = "twice"
