# International & National Prizes
[[national]]
date = "2025"
name = "Chinese Collegiate Computing Competition"
url = ""
prize = "National Second Prize"
role = "Key Member"

[[national]]
date = "2025"
name = "Chinese Collegiate Computing Competition"
url = ""
prize = "National Third Prize"
role = "Key Member"

[[national]]
date = "2025"
name = "China College Students' Service Outsourcing Innovation and Entrepreneurship Competition"
url = ""
prize = "National Third Prize"
role = "Key Member"

[[national]]
date = "2025"
name = "China Undergraduate Life Sciences Contest (Innovation and Entrepreneurship Category)"
url = ""
prize = "National Third Prize"
role = "Key Member"

[[national]]
date = "2024"
name = "China International College Students' Innovation Competition"
url = ""
prize = "International Bronze Medal"
role = "Project Leader"

[[national]]
date = "2024"
name = "ICT Industry-Teaching Integration Innovation Competition"
url = ""
prize = "National Second Prize"
role = "Key Member"

[[national]]
date = "2023"
name = "China International College Students' Innovation Competition"
url = ""
prize = "National Gold Medal"
role = "Key Member"

[[national]]
date = "2023"
name = "China International College Students' Innovation Competition"
url = ""
prize = "International Bronze Medal"
role = "Key Member"

[[national]]
date = "2023"
name = "National Smart Car Competition for College Students"
url = ""
prize = "National First Prize"
role = "Key Member"

# Regional & Provincial Prizes
[[provincial]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = ""
prize = "Provincial Bronze Medal"
role = "Key Member"

[[provincial]]
date = "2025"
name = "Artificial Intelligence Application in Medical Imaging Competition of the Radiology Branch of Guangdong Medical Association"
url = ""
prize = "Provincial Third Prize"
role = "Key Member"

[[provincial]]
date = "2025"
name = "National College Student E-Commerce \"Innovation, Creativity and Entrepreneurship\" Competition"
url = ""
prize = "Provincial Second Prize"
role = "Key Member"

[[provincial]]
date = "2025"
name = "\"Challenge Cup\" National College Student Curricular Academic Science and Technology Works Competition"
url = ""
prize = "Provincial Bronze Medal"
role = "Project Leader"

[[provincial]]
date = "2024"
name = "China International College Students' Innovation Competition"
url = ""
prize = "Provincial Silver Medal"
role = "Project Leader"

[[provincial]]
date = "2024"
name = "\"Challenge Cup\" China College Student Business Plan Competition"
url = ""
prize = "Provincial Bronze Medal"
role = "Key Member"

[[provincial]]
date = "2024"
name = "China College Students' Service Outsourcing Innovation and Entrepreneurship Competition"
url = ""
prize = "Regional Third Prize"
role = "Project Leader"

[[provincial]]
date = "2023"
name = "China International College Students' Innovation Competition"
url = ""
prize = "Provincial Bronze Medal"
role = "Key Member"

