# International & National Prizes
[[national]]
date = "2025"
name = "Chinese Collegiate Computing Competition"
url = "https://jsjds.blcu.edu.cn"
prize = "National First Prize"
role = "Project Leader"

[[national]]
date = "2025"
name = "Chinese Collegiate Computing Competition"
url = "https://jsjds.blcu.edu.cn"
prize = "National Third Prize"
role = "Key Member"

[[national]]
date = "2025"
name = "University Computer Games championship"
url = "http://computergames.caai.cn/"
prize = "National First Prize"
role = "Key Member"

[[national]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = "https://cy.ncss.cn/"
prize = "National Gold Medal"
role = "Project Leader"

[[national]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = "https://cy.ncss.cn/"
prize = "National Bronze Medal"
role = "Key Member"

[[national]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = "https://cy.ncss.cn/"
prize = "International Bronze Medal"
role = "Key Member"

[[national]]
date = "2025"
name = "\"Challenge Cup\" National Undergraduate Extracurricular Academic Science and Technology Works Competition â€” \"Unveiling the List\" Special Track"
url = "https://2025.tiaozhanbei.net/"
prize = "National Second Prize"
role = "Project Leader"

[[national]]
date = "2025"
name = "National Collegiate Biomedical Engineering Competition"
url = "http://www.csbme.org/headline/1476.htm"
prize = "National Second Prize"
role = "Project Leader"

# Regional & Provincial Prizes

[[provincial]]
date = "2025"
name = "China Undergraduate Mathematical Contest in Modeling (CUMCM)"
url = "https://www.mcm.edu.cn/"
prize = "Provincial First Prize"
role = "Project Leader"

[[provincial]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = "https://cy.ncss.cn/"
prize = "Provincial Gold Medal"
role = "Project Leader"

[[provincial]]
date = "2025"
name = "China College Students' Service Outsourcing Innovation and Entrepreneurship Competition"
url = "http://www.fwwb.org.cn/"
prize = "Regional Second Prize"
role = "Project Leader"

[[provincial]]
date = "2025"
name = "China International College Students' Innovation Competition"
url = "https://cy.ncss.cn/"
prize = "Provincial Silver Medal"
role = "Key Member"

