
[[news]]
date = "2025-12"
content = "Our work [VR-Bench](https://mp.weixin.qq.com/s?__biz=MzIzNjc1NzUzMw==&mid=2247851312&idx=3&sn=03d140dd2f6a92a8c17266497d497003&chksm=e945df3f89956b1f95e35ed3b779eb7a93def8b8f365d30eacc52914069187c3f076403148c7&mpshare=1&scene=2&srcid=1210pv20v8Eg9DfF8NrFdcOR&sharer_shareinfo=1892266d409751f86ea02e4b04b7963c&sharer_shareinfo_first=eb3ae1d3145ce5f0faac79e27b316b1b#rd) has been featured by the tech media outlet QbitAI (é‡å­ä½)!"

[[news]]
date = "2025-11"
content = "ğŸš€ [Awesome-Latent-Space](https://github.com/YU-deep/Awesome-Latent-Space) is released!"

[[news]]
date = "2025-11"
content = "Our paper on AI for medical applications has been accepted to AAAI 2026!"
