[[news]]
date = "2025-11"
content = "ðŸš€ [Awesome-Latent-Space](https://github.com/YU-deep/Awesome-Latent-Space) is released!"

[[news]]
date = "2025-11"
content = "Our paper on AI for medical applications has been accepted to AAAI 2026!"
